include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    always_use_package_imports: true
    avoid_print: false
    unawaited_futures: true
    avoid_redundant_argument_values: true
    cancel_subscriptions: true
    close_sinks: true

analyzer:
  errors:
    use_build_context_synchronously: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - build/**